name: check_syntax

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9","3.10","3.11"]
    
    steps:
      - name: Sprawdzenie Repozytorium
        uses: actions/checkout@v2
      
      - name: Ustawianie python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Aktualizowanie pip
        run: |
          python -m pip install --upgrade pip

      - name: Instalowanie flake8
        run: |
          python -m pip install flake8

      - name: Wyświetlanie wersji pythona
        run: python --version

      - name: Analiza kodu za pomoca flake8
        run: |
          flake8 .
