name: main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
      - name: Sprawdzenie Repozytorium
        uses: actions/checkout@v2
      
      - name: Ustawianie python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Aktualizowanie pip
        run: |
          python -m pip install --upgrade pip

      - name: Instalacja flake8 i unittest
        run: |
          pip install flake8 unittest-tools

      - name: Wyświetlanie wersji pythona
        run: python --version

      - name: Analiza kodu za pomoca flake8
        run: |
          flake8 .

      - name: Uruchomienie Unit Testów
        run: |
          python -m unittest discover
